# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epl/protobuf/stac.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from epl.protobuf import geometry_operators_pb2 as epl_dot_protobuf_dot_geometry__operators__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='epl/protobuf/stac.proto',
  package='epl.protobuf',
  syntax='proto3',
  serialized_options=_b('\n\025com.epl.protobuf.stacB\014StacMetadataP\001\242\002\003STC'),
  serialized_pb=_b('\n\x17\x65pl/protobuf/stac.proto\x12\x0c\x65pl.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%epl/protobuf/geometry_operators.proto\"\xe6\x01\n\x0fMetadataRequest\x12\"\n\x05query\x18\x01 \x01(\x0b\x32\x13.epl.protobuf.Query\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x33\n\x0esort_direction\x18\x04 \x01(\x0e\x32\x1b.epl.protobuf.SortDirection\x12+\n\nsort_field\x18\x05 \x01(\x0e\x32\x17.epl.protobuf.FieldName\x12.\n\rresult_fields\x18\x06 \x03(\x0e\x32\x17.epl.protobuf.FieldName\"U\n\x10MetadataResponse\x12+\n\nfield_info\x18\x01 \x03(\x0b\x32\x17.epl.protobuf.FieldInfo\x12\x14\n\x0coffset_index\x18\x02 \x01(\x04\"\xad\x01\n\x05Query\x12 \n\x03\x61nd\x18\x01 \x03(\x0b\x32\x13.epl.protobuf.Query\x12\x1f\n\x02or\x18\x02 \x03(\x0b\x32\x13.epl.protobuf.Query\x12+\n\nfield_info\x18\x03 \x01(\x0b\x32\x17.epl.protobuf.FieldInfo\x12\x34\n\x0crelationship\x18\x04 \x01(\x0e\x32\x1e.epl.protobuf.RelationshipType\"\xe0\x01\n\tFieldInfo\x12*\n\tfieldName\x18\x01 \x01(\x0e\x32\x17.epl.protobuf.FieldName\x12\r\n\x05int64\x18\x02 \x01(\x03\x12\x0e\n\x06\x64ouble\x18\x03 \x01(\x01\x12/\n\x08geometry\x18\x04 \x01(\x0b\x32\x1d.epl.protobuf.GeometryBagData\x12(\n\x04\x62\x62ox\x18\x05 \x01(\x0b\x32\x1a.epl.protobuf.EnvelopeData\x12-\n\tdatetimez\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\\\n\x10RelationshipType\x12\x10\n\x0c\x46IELD_EQUALS\x10\x00\x12\x13\n\x0f\x46IELD_NOT_EQUAL\x10\x01\x12\x11\n\rFIELD_GREATER\x10\x02\x12\x0e\n\nFIELD_LESS\x10\x03*>\n\rSortDirection\x12\x0e\n\nNOT_SORTED\x10\x00\x12\x0e\n\nDESCENDING\x10\x01\x12\r\n\tASCENDING\x10\x02*T\n\tFieldName\x12\x0e\n\nALL_FIELDS\x10\x00\x12\x0f\n\x0b\x45O_GEOMETRY\x10\x01\x12\r\n\tEO_CLOUDS\x10\x02\x12\x0b\n\x07\x45O_BBOX\x10\x03\x12\n\n\x06\x45O_GSD\x10\x04\x42-\n\x15\x63om.epl.protobuf.stacB\x0cStacMetadataP\x01\xa2\x02\x03STCb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,epl_dot_protobuf_dot_geometry__operators__pb2.DESCRIPTOR,])

_RELATIONSHIPTYPE = _descriptor.EnumDescriptor(
  name='RelationshipType',
  full_name='epl.protobuf.RelationshipType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIELD_EQUALS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIELD_NOT_EQUAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIELD_GREATER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIELD_LESS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=836,
  serialized_end=928,
)
_sym_db.RegisterEnumDescriptor(_RELATIONSHIPTYPE)

RelationshipType = enum_type_wrapper.EnumTypeWrapper(_RELATIONSHIPTYPE)
_SORTDIRECTION = _descriptor.EnumDescriptor(
  name='SortDirection',
  full_name='epl.protobuf.SortDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_SORTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DESCENDING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASCENDING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=930,
  serialized_end=992,
)
_sym_db.RegisterEnumDescriptor(_SORTDIRECTION)

SortDirection = enum_type_wrapper.EnumTypeWrapper(_SORTDIRECTION)
_FIELDNAME = _descriptor.EnumDescriptor(
  name='FieldName',
  full_name='epl.protobuf.FieldName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL_FIELDS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EO_GEOMETRY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EO_CLOUDS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EO_BBOX', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EO_GSD', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=994,
  serialized_end=1078,
)
_sym_db.RegisterEnumDescriptor(_FIELDNAME)

FieldName = enum_type_wrapper.EnumTypeWrapper(_FIELDNAME)
FIELD_EQUALS = 0
FIELD_NOT_EQUAL = 1
FIELD_GREATER = 2
FIELD_LESS = 3
NOT_SORTED = 0
DESCENDING = 1
ASCENDING = 2
ALL_FIELDS = 0
EO_GEOMETRY = 1
EO_CLOUDS = 2
EO_BBOX = 3
EO_GSD = 4



_METADATAREQUEST = _descriptor.Descriptor(
  name='MetadataRequest',
  full_name='epl.protobuf.MetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='epl.protobuf.MetadataRequest.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='epl.protobuf.MetadataRequest.limit', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='epl.protobuf.MetadataRequest.offset', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_direction', full_name='epl.protobuf.MetadataRequest.sort_direction', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_field', full_name='epl.protobuf.MetadataRequest.sort_field', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_fields', full_name='epl.protobuf.MetadataRequest.result_fields', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=344,
)


_METADATARESPONSE = _descriptor.Descriptor(
  name='MetadataResponse',
  full_name='epl.protobuf.MetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_info', full_name='epl.protobuf.MetadataResponse.field_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_index', full_name='epl.protobuf.MetadataResponse.offset_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=431,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='epl.protobuf.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='and', full_name='epl.protobuf.Query.and', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='or', full_name='epl.protobuf.Query.or', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_info', full_name='epl.protobuf.Query.field_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relationship', full_name='epl.protobuf.Query.relationship', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=607,
)


_FIELDINFO = _descriptor.Descriptor(
  name='FieldInfo',
  full_name='epl.protobuf.FieldInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fieldName', full_name='epl.protobuf.FieldInfo.fieldName', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64', full_name='epl.protobuf.FieldInfo.int64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double', full_name='epl.protobuf.FieldInfo.double', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='epl.protobuf.FieldInfo.geometry', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bbox', full_name='epl.protobuf.FieldInfo.bbox', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetimez', full_name='epl.protobuf.FieldInfo.datetimez', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=834,
)

_METADATAREQUEST.fields_by_name['query'].message_type = _QUERY
_METADATAREQUEST.fields_by_name['sort_direction'].enum_type = _SORTDIRECTION
_METADATAREQUEST.fields_by_name['sort_field'].enum_type = _FIELDNAME
_METADATAREQUEST.fields_by_name['result_fields'].enum_type = _FIELDNAME
_METADATARESPONSE.fields_by_name['field_info'].message_type = _FIELDINFO
_QUERY.fields_by_name['and'].message_type = _QUERY
_QUERY.fields_by_name['or'].message_type = _QUERY
_QUERY.fields_by_name['field_info'].message_type = _FIELDINFO
_QUERY.fields_by_name['relationship'].enum_type = _RELATIONSHIPTYPE
_FIELDINFO.fields_by_name['fieldName'].enum_type = _FIELDNAME
_FIELDINFO.fields_by_name['geometry'].message_type = epl_dot_protobuf_dot_geometry__operators__pb2._GEOMETRYBAGDATA
_FIELDINFO.fields_by_name['bbox'].message_type = epl_dot_protobuf_dot_geometry__operators__pb2._ENVELOPEDATA
_FIELDINFO.fields_by_name['datetimez'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['MetadataRequest'] = _METADATAREQUEST
DESCRIPTOR.message_types_by_name['MetadataResponse'] = _METADATARESPONSE
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['FieldInfo'] = _FIELDINFO
DESCRIPTOR.enum_types_by_name['RelationshipType'] = _RELATIONSHIPTYPE
DESCRIPTOR.enum_types_by_name['SortDirection'] = _SORTDIRECTION
DESCRIPTOR.enum_types_by_name['FieldName'] = _FIELDNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetadataRequest = _reflection.GeneratedProtocolMessageType('MetadataRequest', (_message.Message,), dict(
  DESCRIPTOR = _METADATAREQUEST,
  __module__ = 'epl.protobuf.stac_pb2'
  # @@protoc_insertion_point(class_scope:epl.protobuf.MetadataRequest)
  ))
_sym_db.RegisterMessage(MetadataRequest)

MetadataResponse = _reflection.GeneratedProtocolMessageType('MetadataResponse', (_message.Message,), dict(
  DESCRIPTOR = _METADATARESPONSE,
  __module__ = 'epl.protobuf.stac_pb2'
  # @@protoc_insertion_point(class_scope:epl.protobuf.MetadataResponse)
  ))
_sym_db.RegisterMessage(MetadataResponse)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'epl.protobuf.stac_pb2'
  # @@protoc_insertion_point(class_scope:epl.protobuf.Query)
  ))
_sym_db.RegisterMessage(Query)

FieldInfo = _reflection.GeneratedProtocolMessageType('FieldInfo', (_message.Message,), dict(
  DESCRIPTOR = _FIELDINFO,
  __module__ = 'epl.protobuf.stac_pb2'
  # @@protoc_insertion_point(class_scope:epl.protobuf.FieldInfo)
  ))
_sym_db.RegisterMessage(FieldInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
