version: '3'
services:
  naip-stac-grpc:
    container_name: naip-stac-grpc-service-c
    image: us.gcr.io/echoparklabs/naip-stac-grpc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - naip
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    container_name: naip-stac-grpc-db-c
    image: mdillon/postgis
    ports:
      - "5432:5432"
    networks:
      - naip
    environment:
      - POSTGRES_PASSWORD=cabbage
      - POSTGRES_USER=user
      - POSTGRES_DB=testdb

networks:
  naip: {}